import { CalendarDays, Cloud, Copy, ExternalLink, ImageOff, Play, RotateCcw, Trash2 } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { PageIntro, StyleShell } from "@/components/StyleShell";
import { useAppState } from "@/lib/styleData";
import { toast } from "sonner";

export default function Gallery() {
  const [state, commit, syncToAccount, isAuthenticated, syncing] = useAppState();
  const remove = (id: string) => { commit((current) => ({ ...current, gallery: current.gallery.filter((look) => look.id !== id) })); toast.success("Look removed from Gallery."); };
  const copyLook = async (lookId: string) => { const link = `${window.location.origin}/gallery#${lookId}`; try { await navigator.clipboard.writeText(link); toast.success("Gallery link copied."); } catch { toast.info("Copy is unavailable here. Your look is still saved locally in Gallery."); } };
  const saveToAccount = async () => { if (!isAuthenticated) { toast.info("Sign in from the profile button to save Gallery looks across devices."); return; } try { await syncToAccount(); toast.success("Gallery saved to your account."); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not save your Gallery."); } };
  return <StyleShell><main className="mx-auto max-w-[1320px] px-5 py-10 lg:px-10 lg:py-14"><PageIntro eyebrow="Your saved experiments" title="My Gallery" description="The looks you liked enough to keep. Reuse the same photo, swap a piece, or copy a link to this saved composition." action={<div className="flex flex-wrap justify-end gap-2"><Button variant="outline" className="rounded-full bg-white" onClick={saveToAccount} disabled={syncing}><Cloud size={16} /> {syncing ? "Saving…" : "Save to account"}</Button><Link href="/try-on"><Button className="rounded-full bg-[#18152B] text-white hover:bg-[#37314f]"><Play size={16} /> Create a new look</Button></Link></div>} />
    {!state.gallery.length ? <div className="grid items-center gap-8 rounded-[30px] bg-white p-8 shadow-sm md:grid-cols-[.85fr_1.15fr] md:p-12"><div><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#FFD166]"><ImageOff size={20} /></div><h2 className="mt-7 font-display text-4xl leading-[.92] tracking-[-.055em]">Nothing saved<br /><em className="font-serif font-normal text-[#FF6B57]">yet.</em></h2><p className="mt-4 max-w-sm text-sm leading-6 text-[#18152B]/55">Choose two real Closet pieces, let AI curate the pairing, and save the first version worth remembering.</p><Link href="/try-on"><Button className="mt-7 rounded-full bg-[#FF6B57] text-[#18152B] hover:bg-[#ff836f]">Enter the fitting room <ExternalLink size={15} /></Button></Link></div><img src="/manus-storage/spring-flatlay_4fb5b884.jpg" alt="Flat-lay of wardrobe pieces" className="h-[280px] w-full rounded-[22px] object-cover mix-blend-multiply md:h-[350px]" /></div> : <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{state.gallery.map((look) => { const items = state.items.filter((item) => look.itemIds.includes(item.id)); return <article id={look.id} key={look.id} className="overflow-hidden rounded-[26px] bg-white p-3 shadow-sm"><div className="relative aspect-[.9] overflow-hidden rounded-[20px] bg-[#E6DEFF]"><img src={look.photo} alt={look.title} className="h-full w-full object-cover" /><div className="absolute inset-x-3 bottom-3 flex items-center justify-between rounded-xl bg-[#18152B]/75 px-3 py-2 text-xs text-white backdrop-blur"><span>{new Date(look.date).toLocaleDateString()}</span><span className="text-[#78D5B0]">AI or manual preview</span></div></div><div className="p-3"><div className="flex items-start justify-between gap-4"><div><h2 className="font-display text-2xl tracking-[-.04em]">{look.title}</h2><p className="mt-1 text-xs text-[#18152B]/45">{look.itemNames.join(" · ")}</p></div><button onClick={() => remove(look.id)} className="text-[#18152B]/30 hover:text-[#FF6B57]" aria-label="Delete saved look"><Trash2 size={16} /></button></div><div className="mt-4 flex gap-2"><Link href={`/try-on?items=${look.itemIds.slice(0, 2).join(",")}`} className="flex-1"><Button variant="outline" className="w-full rounded-full"><RotateCcw size={14} /> Reuse</Button></Link><button onClick={() => copyLook(look.id)} className="flex h-10 w-10 items-center justify-center rounded-full bg-[#F3F1FF] text-[#18152B]/55 hover:text-[#5B5CE2]" aria-label="Copy gallery link"><Copy size={17} /></button></div>{items.length ? <div className="mt-4 grid grid-cols-3 gap-1.5">{items.map((item) => <img key={item.id} src={item.image} alt={item.name} className="aspect-square w-full rounded-lg object-cover mix-blend-multiply" />)}</div> : <div className="mt-4 rounded-xl bg-[#FFF0EC] p-3 text-xs text-[#18152B]/55">One or more Closet pieces were removed, but the original preview is preserved.</div>}</div></article>; })}</div>}
    <div className="mt-12 flex items-center gap-2 text-xs text-[#18152B]/40"><CalendarDays size={14} /> Saved looks stay private in this browser preview until account persistence is connected.</div>
  </main></StyleShell>;
}
