import { useEffect, useMemo, useRef, useState } from "react";
import { Camera, Check, ChevronDown, ImagePlus, RotateCcw, Save, Search, Shirt, Sparkles, Upload, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PageIntro, StyleShell } from "@/components/StyleShell";
import { type StyleItem, useAppState } from "@/lib/styleData";
import { toast } from "sonner";

const demoPhoto = "/manus-storage/neutral-look_116aef4f.jpeg";

export default function TryOn() {
  const [state, commit] = useAppState();
  const [photo, setPhoto] = useState(demoPhoto);
  const [photoLabel, setPhotoLabel] = useState("Demo portrait");
  const [selected, setSelected] = useState<string[]>([]);
  const [search, setSearch] = useState("");
  const [scale, setScale] = useState(100);
  const [positionY, setPositionY] = useState(35);
  const [rotation, setRotation] = useState(0);
  const [opacity, setOpacity] = useState(88);
  const [cameraOpen, setCameraOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [showAttributes, setShowAttributes] = useState(false);
  const photoInput = useRef<HTMLInputElement>(null);
  const garmentInput = useRef<HTMLInputElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const queryIds = useMemo(() => new URLSearchParams(window.location.search).get("items")?.split(",").filter(Boolean) ?? [], []);
  useEffect(() => { if (queryIds.length) setSelected(queryIds); }, [queryIds]);
  const selectedItems = state.items.filter((item) => selected.includes(item.id));
  const results = state.items.filter((item) => !selected.includes(item.id) && (!search || `${item.name} ${item.category} ${item.color}`.toLowerCase().includes(search.toLowerCase()))).slice(0, 8);
  const uploadPhoto = (file?: File) => { if (!file) return; if (!file.type.startsWith("image/")) { toast.error("That file is not an image we can use."); return; } const reader = new FileReader(); reader.onload = () => { setPhoto(String(reader.result)); setPhotoLabel(file.name); toast.success("Photo ready for a basic preview."); }; reader.readAsDataURL(file); };
  const uploadGarment = (file?: File) => { if (!file) return; if (!file.type.startsWith("image/")) { toast.error("Please upload a JPG, PNG, or WEBP garment photo."); return; } const reader = new FileReader(); reader.onload = () => { const id = `upload-${Date.now()}`; const newItem: StyleItem = { id, name: file.name.replace(/\.[^/.]+$/, "").replace(/[-_]/g, " "), category: "Tops", color: "New", style: "Your edit", occasion: ["everyday"], formality: 3, image: String(reader.result), source: "upload", createdAt: Date.now() }; commit((current) => ({ ...current, items: [newItem, ...current.items] })); setSelected((ids) => [...ids, id]); toast.success("Garment added to Closet and selected here."); }; reader.readAsDataURL(file); };
  const useCamera = async () => { try { const stream = await navigator.mediaDevices.getUserMedia({ video: true }); streamRef.current = stream; setCameraOpen(true); window.setTimeout(() => { if (videoRef.current) videoRef.current.srcObject = stream; }, 50); } catch { toast.error("Camera access was unavailable. You can still upload a photo instead."); } };
  const capture = () => { const video = videoRef.current; if (!video) return; const canvas = document.createElement("canvas"); canvas.width = video.videoWidth || 720; canvas.height = video.videoHeight || 960; canvas.getContext("2d")?.drawImage(video, 0, 0, canvas.width, canvas.height); setPhoto(canvas.toDataURL("image/jpeg", .86)); setPhotoLabel("Camera capture"); streamRef.current?.getTracks().forEach((track) => track.stop()); setCameraOpen(false); toast.success("Camera capture ready."); };
  const closeCamera = () => { streamRef.current?.getTracks().forEach((track) => track.stop()); setCameraOpen(false); };
  const saveLook = () => { if (!selectedItems.length) { toast.error("Select at least one real closet piece first."); return; } setSaving(true); window.setTimeout(() => { commit((current) => ({ ...current, gallery: [{ id: `look-${Date.now()}`, title: `${selectedItems[0].style} preview`, date: Date.now(), photo, itemIds: selectedItems.map((item) => item.id), itemNames: selectedItems.map((item) => item.name) }, ...current.gallery] })); setSaving(false); toast.success("Saved to your Gallery."); }, 450); };
  return <StyleShell><main className="mx-auto max-w-[1320px] px-5 py-10 lg:px-10 lg:py-14"><PageIntro eyebrow="The fitting room" title="Try it on, before you buy." description="Use your real photo and real closet pieces to compose a basic preview. No fake provider result, no invented clothing—just an adjustable visual starting point." action={<Button onClick={saveLook} disabled={saving || !selectedItems.length} className="rounded-full bg-[#FF6B57] text-[#18152B] hover:bg-[#ff836f]"><Save size={16} /> {saving ? "Saving…" : "Save to Gallery"}</Button>} />
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_420px]"><section className="rounded-[28px] bg-[#18152B] p-4 text-white md:p-6"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><span className="rounded-full bg-[#FFD166] px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.15em] text-[#18152B]">Basic Preview</span><p className="mt-3 text-sm text-white/50">No AI fitting provider connected · adjust manually below</p></div><button onClick={() => { setPhoto(demoPhoto); setPhotoLabel("Demo portrait"); }} className="flex items-center gap-2 text-xs font-medium text-white/55 hover:text-white"><RotateCcw size={14} /> Reset photo</button></div><div className="relative mx-auto aspect-[.72] max-h-[670px] w-full max-w-[520px] overflow-hidden rounded-[24px] bg-[#E7DCCF]"><img src={photo} alt="Your try-on base photo" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#18152B]/25 via-transparent to-transparent" />{selectedItems.length ? <div className="absolute left-1/2 w-[68%] transition-all duration-200" style={{ top: `${positionY}%`, transform: `translate(-50%, -50%) rotate(${rotation}deg) scale(${scale / 100})`, opacity: opacity / 100 }}><img src={selectedItems[0].image} alt={`${selectedItems[0].name} overlay`} className="w-full rounded-[18px] object-cover mix-blend-multiply shadow-2xl" /><div className="absolute -right-3 -top-3 rounded-full bg-[#FFD166] px-2 py-1 text-[9px] font-bold text-[#18152B]">manual layer</div></div> : <div className="absolute inset-x-8 top-1/2 -translate-y-1/2 rounded-2xl border border-dashed border-white/40 bg-[#18152B]/35 p-6 text-center backdrop-blur-sm"><Shirt className="mx-auto mb-3 text-[#FFD166]" /><p className="font-display text-2xl">Select a piece<br />to start layering.</p><p className="mt-2 text-xs text-white/65">The original photo stays untouched underneath.</p></div>}<div className="absolute bottom-4 left-4 right-4 flex items-center justify-between rounded-2xl bg-[#18152B]/75 px-4 py-3 text-xs backdrop-blur"><span className="max-w-[70%] truncate">{photoLabel}</span><span className="text-[#FFD166]">{selectedItems.length} piece{selectedItems.length === 1 ? "" : "s"} selected</span></div></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><Control label="Scale" value={scale} min={65} max={140} onChange={setScale} /><Control label="Position" value={positionY} min={18} max={70} onChange={setPositionY} /><Control label="Opacity" value={opacity} min={45} max={100} onChange={setOpacity} /></div><div className="mt-4"><label className="mb-2 block text-xs text-white/45">Rotation</label><input aria-label="Rotation" type="range" min={-12} max={12} value={rotation} onChange={(e) => setRotation(Number(e.target.value))} className="w-full accent-[#FF6B57]" /></div></section>
    <aside className="space-y-4"><section className="rounded-[26px] bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#FF6B57]">01 / Your photo</p><h2 className="mt-1 font-display text-2xl tracking-[-.04em]">Start with a frame</h2></div><ImagePlus size={20} className="text-[#5B5CE2]" /></div><div className="grid grid-cols-2 gap-2"><input ref={photoInput} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={(e) => uploadPhoto(e.target.files?.[0])} /><Button variant="outline" className="h-auto rounded-xl py-3" onClick={() => photoInput.current?.click()}><Upload size={15} /> Upload</Button><Button variant="outline" className="h-auto rounded-xl py-3" onClick={useCamera}><Camera size={15} /> Use camera</Button></div><p className="mt-3 text-[11px] leading-5 text-[#18152B]/45">JPG, PNG, or WEBP. Camera permission is optional; uploads still work if it’s denied.</p>{cameraOpen && <div className="mt-4 overflow-hidden rounded-xl bg-[#18152B]"><video ref={videoRef} autoPlay playsInline className="aspect-[.8] w-full object-cover" /><div className="flex gap-2 p-2"><Button onClick={capture} className="flex-1 rounded-full bg-[#FFD166] text-[#18152B]">Capture</Button><Button onClick={closeCamera} variant="outline" className="rounded-full border-white/20 text-white">Cancel</Button></div></div>}</section>
      <section className="rounded-[26px] bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#5B5CE2]">02 / Select a piece</p><h2 className="mt-1 font-display text-2xl tracking-[-.04em]">From your Closet</h2></div><LinkIcon /></div><div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#18152B]/35" /><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search your pieces…" className="rounded-xl pl-9" /></div><div className="mt-3 max-h-[270px] space-y-2 overflow-y-auto pr-1">{results.map((item) => <button key={item.id} onClick={() => setSelected((ids) => ids.includes(item.id) ? ids.filter((id) => id !== item.id) : [...ids, item.id])} className={`flex w-full items-center gap-3 rounded-xl p-2 text-left transition ${selected.includes(item.id) ? "bg-[#FFF0EC] ring-1 ring-[#FF6B57]" : "bg-[#F8F7FF] hover:bg-[#F0EEFF]"}`}><img src={item.image} alt="" className="h-12 w-12 rounded-lg object-cover mix-blend-multiply" /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{item.name}</span><span className="block text-[11px] text-[#18152B]/45">{item.category} · {item.color}</span></span>{selected.includes(item.id) ? <Check size={16} className="text-[#FF6B57]" /> : <span className="text-xs text-[#18152B]/35">Add</span>}</button>)}<input ref={garmentInput} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={(e) => uploadGarment(e.target.files?.[0])} />{!results.length && <p className="py-4 text-center text-xs text-[#18152B]/45">No matching closet pieces.</p>}</div><Button onClick={() => garmentInput.current?.click()} variant="outline" className="mt-3 w-full rounded-xl border-dashed"><Upload size={15} /> Upload a new garment to Closet</Button></section>
      <section className="rounded-[26px] bg-[#E6DEFF] p-5"><button onClick={() => setShowAttributes((v) => !v)} className="flex w-full items-center justify-between text-left"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#5B5CE2]">03 / Your context</p><h2 className="mt-1 font-display text-2xl tracking-[-.04em]">Set the Scene defaults</h2></div><ChevronDown size={18} className={`transition-transform ${showAttributes ? "rotate-180" : ""}`} /></button>{showAttributes && <div className="mt-5 space-y-3 border-t border-[#5B5CE2]/15 pt-4 text-sm"><div className="flex justify-between"><span className="text-[#18152B]/50">Gender</span><span className="font-semibold">{state.profile.gender || "Not set"}</span></div><div className="flex justify-between"><span className="text-[#18152B]/50">Undertone</span><span className="font-semibold">{state.profile.undertone || "Not set"}</span></div><p className="pt-1 text-[11px] leading-5 text-[#18152B]/50">Editable per session in a connected provider flow. Your saved profile is never re-asked.</p></div>}</section></aside></div>
  </main></StyleShell>;
}
function Control({ label, value, min, max, onChange }: { label: string; value: number; min: number; max: number; onChange: (value: number) => void }) { return <label className="text-xs text-white/45"><span className="mb-2 flex justify-between"><span>{label}</span><span className="text-white/80">{value}{label === "Position" ? "%" : ""}</span></span><input aria-label={label} type="range" min={min} max={max} value={value} onChange={(e) => onChange(Number(e.target.value))} className="w-full accent-[#FF6B57]" /></label>; }
function LinkIcon() { return <span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#F3F1FF]"><Sparkles size={16} className="text-[#5B5CE2]" /></span>; }
